### ISSUE TITLE
Show only months

### ISSUE THREAD

**Issue by iBasit** [jonmiles/bootstrap-datepaginator#17]
I want to show months only, is it possible?

**Comment by jonmiles** [comment]
No, sorry... but I will add this to possible future enhancements.

**Comment by iBasit** [comment]
I can pay you to add it, so it can be added quickly. I need it for one of
our application.


Best Regards
Basit

Live Your Life with Inspiration
http://Basit.me

**Comment by jonmiles** [comment]
You can hire me on Elance @ http://jonathandanielmiles.elance.com.

**Comment by iBasit** [comment]
how much it will cost? for this task?


Best Regards
Basit

Live Your Life with Inspiration
http://Basit.me

**Comment by jonmiles** [comment]
What are your exact requirements?  I work by the hour, my rate is on Elance... may be it's a couple of hours works, really depends on your exact requirements.

**Comment by iBasit** [comment]
I Got it working for months. Just replaced 'day' and 'days' to 'month' and it starts working :)

![image](https://cloud.githubusercontent.com/assets/34341/7127704/c440d540-e23f-11e4-86f7-7924cf46d4b4.png)
