### ISSUE TITLE
Need some more functional information

### ISSUE THREAD

**Issue by VickyMahir** [jonmiles/bootstrap-datepaginator#21]
Hi John

I have seen your date paginator it working fine.

But i need some more functionality from you so can you please guide me?

I want to add date paginator with table ( responsive that table as per date paginator. ) 

For more information see attached image.

So please tell me how to do that.

Thanks  

Vijay Maheriya
![availability](https://cloud.githubusercontent.com/assets/5336761/7610073/786ee048-f997-11e4-9bd4-355bd9dedc6f.jpg)

**Comment by jonmiles** [comment]
You could use the `selectedDateChanged` event to update the table when the paginator is clicked.

However, adding a table to the paginator or attempting is keep the two in sync is clearly out of scope.  It would be down to you, to implement this functionality.

**Comment by VickyMahir** [comment]
Thanks for reply

Date paginator update after resize ( Means you are show hide cell on width of device ) so how to update my table after resize like date paginator? 

I want to just resizing functionality for my table so please tell me if you have any suggestion 

Thanks

Vijay Maheriya

**Comment by jonmiles** [comment]
Your best bet is to look in the date-paginator code, basically it's dynamically calculated.

**Comment by VickyMahir** [comment]
ok john i will look into code and thanks for help

Thanks

Vijay Maheriya
