### ISSUE TITLE
does not show selected date

### ISSUE THREAD

**Issue by alissonbarison** [jonmiles/bootstrap-datepaginator#27]
bootstrap-datepaginator does not show the selected day when the sta date between 10/19/2015 and 02/11/2015

**Comment by jonmiles** [comment]
Looks like your dates / date formats are wrong, there are no selectable dates between 19th Oct 2015 and 11th of February 2015 ?

**Comment by alissonbarison** [comment]
http://www.jondmiles.com/bootstrap-datepaginator/
not even in the site  http://www.jondmiles.com/bootstrap-datepaginator/ appears today's date slecionada only after the day 10/25/2015

**Comment by jonmiles** [comment]
No that site works as I designed it, the selected date works and all the tests pass.

Either you're confused on how the date paginator works, or you're not explaining yourself very well.

**Comment by alissonbarison** [comment]
Until yesterday the bootstrap-datepaginator displayed the selected day different and today show how every other day, on the page of bootstrap-datepaginator soon in the case of top click on the day and you'll see what I mean

**Comment by alissonbarison** [comment]
Did you understand what I said?

**Comment by jonmiles** [comment]
Sorry I have no idea what you mean.

Nothing has changed since yesterday, I haven't touched this project in 2
years.  I see no issue with date selection, the demo works as it always has.

On Monday, 19 October 2015, alissonbarison <notifications@github.com> wrote:

> Did you understand what I said?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonmiles/bootstrap-datepaginator/issues/27#issuecomment-149316115>
> .
>


-- 
Regards
Jon Miles

**Comment by jonmiles** [comment]
Sorry I have no idea what you mean.

Nothing has changed since yesterday, I haven't touched this project in 2
years.  I see no issue with date selection, the demo works as it always has.

On Monday, 19 October 2015, alissonbarison <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Did you understand what I said?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jonmiles/bootstrap-datepaginator/issues/27#issuecomment-149316115>
> .
>


-- 
Regards
Jon Miles

**Comment by alissonbarison** [comment]
![image](https://cloud.githubusercontent.com/assets/4990115/10605687/cb9c63aa-7703-11e5-97ba-82570b3d82ce.jpg)
see de image.

**Comment by alissonbarison** [comment]
![image](https://cloud.githubusercontent.com/assets/4990115/10605726/1746a9b4-7704-11e5-8f77-06bff2cd9dc3.jpg)
see de image

**Comment by jonmiles** [comment]
Thanks for the clarification, that's helpful.  What browser?  Do you have any console errors?

The demo on http://www.jondmiles.com/bootstrap-datepaginator/ works OK for me.  Are you saying it doesn't work for you when you visit http://www.jondmiles.com/bootstrap-datepaginator?

**Comment by alissonbarison** [comment]
Google Chrome - 46.0.2490.71
error in console: GET http://www.jondmiles.com/bootstrap-datepaginator/js/ga.js 
only that

**Comment by jonmiles** [comment]
I really not sure why you're experiencing this problem.  

I've just updated Chrome to same release as you report, and as you can see from the screenshot it works for me.

![image](https://cloud.githubusercontent.com/assets/1718611/10606503/4b36c822-772b-11e5-97d9-310ad74481ad.png)

**Comment by alissonbarison** [comment]
![image3](https://cloud.githubusercontent.com/assets/4990115/10607290/f59bc712-770e-11e5-952a-e62769185f2a.jpg)
here with console log

**Comment by jonmiles** [comment]
Thanks, I can see now that it doesn't work for you!

It works for me, and my colleagues who have just tried the same URL.  No other users have reported this issue, so I suggest it's environmental and the only advice I can provide is to try and debug the issues yourself.
